# RankUp Plugin made by esh123cookie 
# Plugin made for people who cannot find an updated version for rankup
# To use this plugin you will need pureperms and purechat

# version 2.0.0
# Simple rankup plugin 

# ranks 

A:
  rank: "A"
  price: "50"
#commands next
